#!/usr/bin/env python3
"""Generate one SQLLogicTest port specification per GQL clause feature file.

The generated files are a complete, source-mapped porting surface. They live
outside ``test/sql`` because a source scenario is not executable until its
fixture and assertions have been reviewed. Reviewed implementations remain in
``test/sql`` and are linked through ``test/features/execution.tsv``.
"""

from __future__ import annotations

import csv
import re
import shutil
from collections import defaultdict
from pathlib import Path

from gql_fixture_adapter import (
    FixtureAdaptationError,
    compile_fixture_sql,
    parse_insert_fixture,
    safe_name,
)


ROOT = Path(__file__).resolve().parents[1]
FEATURE_ROOT = ROOT / "test" / "features"
CORPUS = FEATURE_ROOT / "clauses"
OUTPUT = FEATURE_ROOT / "sqllogic" / "clauses"
INDEX = FEATURE_ROOT / "sqllogic" / "manifest.tsv"
FIXTURE_INDEX = FEATURE_ROOT / "sqllogic" / "fixtures.tsv"


def load_tsv(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8", newline="") as source:
        return list(csv.DictReader(source, delimiter="\t"))


def scenario_blocks(path: Path) -> list[tuple[str, str]]:
    lines = path.read_text(encoding="utf-8").splitlines()
    starts: list[tuple[int, str]] = []
    for index, line in enumerate(lines):
        match = re.match(r"^\s*Scenario(?: Outline)?:\s*(.+)$", line)
        if match:
            starts.append((index, match.group(1).strip()))
    result: list[tuple[str, str]] = []
    for ordinal, (start, name) in enumerate(starts):
        end = starts[ordinal + 1][0] if ordinal + 1 < len(starts) else len(lines)
        block = "\n".join(lines[start:end]).rstrip()
        result.append((name, block))
    return result


def background_text(path: Path) -> str:
    text = path.read_text(encoding="utf-8")
    first_scenario = re.search(r"(?m)^\s*Scenario(?: Outline)?:", text)
    return text[: first_scenario.start()] if first_scenario else text


def comment_block(text: str) -> str:
    return "\n".join("# " + line if line else "#" for line in text.splitlines())


def having_executed_blocks(text: str) -> list[str]:
    lines = text.splitlines()
    result: list[str] = []
    index = 0
    while index < len(lines):
        if not re.search(r"\bhaving executed:\s*$", lines[index], re.I):
            index += 1
            continue
        index += 1
        while index < len(lines) and lines[index].strip() != '"""':
            index += 1
        if index == len(lines):
            raise SystemExit("having executed step has no query doc string")
        start = index + 1
        index = start
        while index < len(lines) and lines[index].strip() != '"""':
            index += 1
        if index == len(lines):
            raise SystemExit("having executed step has an unterminated query doc string")
        result.append("\n".join(lines[start:index]).strip())
        index += 1
    return result


def output_path(target_path: str) -> Path:
    return OUTPUT / Path(target_path).with_suffix(".test")


def main() -> int:
    manifest_rows = load_tsv(CORPUS / "manifest.tsv")
    execution_rows = load_tsv(FEATURE_ROOT / "execution.tsv")
    executions = {
        (row["source_path"], row["source_line"]): row for row in execution_rows
    }
    by_target: dict[str, list[dict[str, str]]] = defaultdict(list)
    for row in manifest_rows:
        by_target[row["target_path"]].append(row)

    if OUTPUT.exists():
        shutil.rmtree(OUTPUT)
    OUTPUT.mkdir(parents=True)

    index_rows: list[list[object]] = []
    fixture_index_rows: list[list[object]] = []
    for target_path in sorted(by_target):
        rows = by_target[target_path]
        source_feature = CORPUS / target_path
        blocks = scenario_blocks(source_feature)
        background_blocks = having_executed_blocks(background_text(source_feature))
        if [name for name, _ in blocks] != [row["scenario"] for row in rows]:
            raise SystemExit(f"scenario order mismatch in {target_path}")

        target = output_path(target_path)
        target.parent.mkdir(parents=True, exist_ok=True)
        relative_target = target.relative_to(ROOT).as_posix()
        executable_count = sum(
            executions.get((row["source_path"], row["source_line"]), {}).get(
                "status"
            )
            == "executable"
            for row in rows
        )
        fixture_setup_count = 0
        fixture_ready_count = 0
        contents = [
            f"# name: {relative_target}",
            f"# description: SQLLogicTest port specification for {target_path}",
            "# group: [gql]",
            "#",
            "# GENERATED by scripts/generate_gql_clause_sqllogic.py; do not edit.",
            f"# Source: test/features/clauses/{target_path}",
            "# Derived from the Apache-2.0 openCypher TCK corpus pinned in",
            "# test/features/clauses/SOURCE.json; retain LICENSE and NOTICE.",
            "#",
            "# This file is the complete SQLLogic port specification, not an",
            "# executable pass claim. Scenarios move into test/sql only after",
            "# fixture adaptation and semantic assertions have been reviewed.",
            "",
        ]
        for row, (scenario_name, scenario_text) in zip(rows, blocks):
            key = (row["source_path"], row["source_line"])
            execution = executions.get(key)
            status = execution["status"] if execution else "pending"
            contents.extend(
                [
                    f"# Source: {row['source_path']}:{row['source_line']} {scenario_name}",
                    f"# Port status: {status}",
                    f"# Translation review flags: {row['blockers']}",
                ]
            )
            if execution and execution["test_path"]:
                contents.append(f"# Executable test: {execution['test_path']}")
            if execution and execution["notes"]:
                contents.append(f"# Review notes: {execution['notes']}")
            setup_blocks = background_blocks + having_executed_blocks(scenario_text)
            if setup_blocks:
                fixture_setup_count += 1
                setup_query = "\n".join(setup_blocks)
                fixture_name = safe_name(
                    f"port_{Path(target_path).stem}_{row['source_line']}"
                )
                try:
                    fixture = parse_insert_fixture(setup_query)
                    fixture_sql = compile_fixture_sql(setup_query, fixture_name)
                    fixture_status = "ready"
                    fixture_reason = ""
                    fixture_ready_count += 1
                    contents.extend(
                        [
                            "# INSERT fixture adaptation: ready",
                            "# SQLLogic fixture setup:",
                            comment_block(fixture_sql),
                        ]
                    )
                except FixtureAdaptationError as error:
                    fixture = None
                    fixture_status = "pending"
                    fixture_reason = " ".join(str(error).split())
                    contents.append(
                        f"# INSERT fixture adaptation: pending - {fixture_reason}"
                    )
                fixture_index_rows.append(
                    [
                        row["source_path"],
                        row["source_line"],
                        relative_target,
                        fixture_status,
                        len(fixture.nodes) if fixture else 0,
                        len(fixture.edges) if fixture else 0,
                        fixture_reason,
                    ]
                )
            contents.extend(
                [
                    "#",
                    "# GQL-adapted source specification:",
                    comment_block(scenario_text),
                    "",
                ]
            )
        target.write_text("\n".join(contents).rstrip() + "\n", encoding="utf-8")
        index_rows.append(
            [
                f"test/features/clauses/{target_path}",
                relative_target,
                len(rows),
                executable_count,
                len(rows) - executable_count,
                fixture_setup_count,
                fixture_ready_count,
                fixture_setup_count - fixture_ready_count,
            ]
        )

    INDEX.parent.mkdir(parents=True, exist_ok=True)
    with INDEX.open("w", encoding="utf-8", newline="") as output:
        writer = csv.writer(output, delimiter="\t", lineterminator="\n")
        writer.writerow(
            [
                "source_feature",
                "port_test",
                "scenarios",
                "executable",
                "pending",
                "fixture_setups",
                "fixture_ready",
                "fixture_pending",
            ]
        )
        writer.writerows(index_rows)
    with FIXTURE_INDEX.open("w", encoding="utf-8", newline="") as output:
        writer = csv.writer(output, delimiter="\t", lineterminator="\n")
        writer.writerow(
            [
                "source_path",
                "source_line",
                "port_test",
                "status",
                "vertices",
                "edges",
                "reason",
            ]
        )
        writer.writerows(fixture_index_rows)
    print(
        f"generated {len(index_rows)} SQLLogic port files covering "
        f"{len(manifest_rows)} scenarios; adapted "
        f"{sum(row[3] == 'ready' for row in fixture_index_rows)}/"
        f"{len(fixture_index_rows)} INSERT fixture setups"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
