#!/usr/bin/env python3
"""Promote passing source-equivalent GQL candidates into the active suite."""

from __future__ import annotations

import argparse
import csv
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
EXECUTION = ROOT / "test" / "features" / "execution.tsv"


def load_tsv(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8", newline="") as source:
        return list(csv.DictReader(source, delimiter="\t"))


def candidate_body(path: Path) -> str:
    lines = path.read_text(encoding="utf-8").splitlines()
    result: list[str] = []
    for line in lines:
        if line.startswith("# name:") or line == "# group: [gql]":
            continue
        if line == "require gql":
            continue
        result.append(line)
    while result and not result[0]:
        result.pop(0)
    while result and not result[-1]:
        result.pop()
    return "\n".join(result)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--candidates", type=Path, required=True)
    parser.add_argument("--runner", type=Path, required=True)
    parser.add_argument(
        "--output",
        type=Path,
        default=ROOT / "test" / "sql" / "gql_feature_compatibility.test",
    )
    arguments = parser.parse_args()
    candidate_root = arguments.candidates.resolve()
    runner = arguments.runner.resolve()
    output = arguments.output.resolve()

    promoted: list[tuple[dict[str, str], Path]] = []
    for row in load_tsv(candidate_root / "manifest.tsv"):
        candidate = Path(row["test_path"])
        completed = subprocess.run(
            [str(runner), candidate.relative_to(ROOT).as_posix()],
            cwd=ROOT,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            check=False,
        )
        if completed.returncode == 0 and "All tests passed" in completed.stdout:
            promoted.append((row, candidate))

    relative_output = output.relative_to(ROOT).as_posix()
    contents = [
        f"# name: {relative_output}",
        "# description: Verified scalar-result openCypher clause compatibility",
        "# group: [gql]",
        "#",
        "# GENERATED by scripts/promote_gql_executable_candidates.py.",
        "# Each source-equivalent ISO-GQL adaptation passed independently before",
        "# inclusion here. Source licensing is retained under test/features/clauses.",
        "",
        "require gql",
        "",
    ]
    for _, candidate in promoted:
        contents.extend([candidate_body(candidate), ""])
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(contents).rstrip() + "\n", encoding="utf-8")

    fieldnames = ["source_path", "source_line", "status", "test_path", "notes"]
    execution_rows = [
        row for row in load_tsv(EXECUTION) if row["test_path"] != relative_output
    ]
    existing = {
        (row["source_path"], row["source_line"]): row for row in execution_rows
    }
    for row, _ in promoted:
        key = (row["source_path"], row["source_line"])
        if key in existing:
            continue
        promoted_row = {
            "source_path": row["source_path"],
            "source_line": row["source_line"],
            "status": "executable",
            "test_path": relative_output,
            "notes": (
                "Scalar-result source scenario translated to ISO GQL and verified "
                "against its adapted native-table fixture"
            ),
        }
        execution_rows.append(promoted_row)
        existing[key] = promoted_row
    execution_rows.sort(key=lambda row: (row["source_path"], int(row["source_line"])))
    with EXECUTION.open("w", encoding="utf-8", newline="") as destination:
        writer = csv.DictWriter(
            destination, fieldnames=fieldnames, delimiter="\t", lineterminator="\n"
        )
        writer.writeheader()
        writer.writerows(execution_rows)

    print(
        f"promoted {len(promoted)} passing candidates to {relative_output}; "
        f"execution manifest now has {len(execution_rows)} rows"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
